home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout")
]

login_signup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('send_code/', views.send_code),
    path('login/', views.login, name="login"),
    path('register_page/', views.register_page, name='register_page'),
    path('register/', views.register, name="register"),
    path('login_page/', views.login_page, name="login_page")
]

mystone/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexmystone, name="indexmystone"),
    path('new/', views.newindex, name='newindex'),
    path('savegame/', views.savegame, name='savegame'),
    path('savedata/', views.savedata, name='savedata')
]

others/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name="about"),
    path('complain/', views.write_advice, name='complain'),
    path('media/', views.media, name='media'),
    path('newmain/', views.newmain, name='newmain'),
    path('user/', views.user1, name='user1'),
    path('user2/', views.user2, name='user2'),
    path('stone/', views.stone, name='shimo'),
    path('main_part/', views.main_part, name='main_part')
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:page>', views.list_page, name='list'),
    path('content/<int:post_id>', views.content_page, name='content'),
    path('release/', views.release, name='release'),
    path('search/', views.search, name='search'),
    path('comment/<int:post_id>', views.follow, name='follow')

]

stone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_signup/', include(('login_signup.urls', 'login_signup'), namespace='login_signup')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('others/', include(('others.urls', 'others'), namespace='others')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('manage/', include(('backmanage.urls', 'backmanage'), namespace='backmanage')),
    path('mystone/', include(('mystone.urls', 'mystone'), namespace='mystone')),
    path('fullview/', include(('fullview.urls', 'fullview'), namespace='fullview'))
]

home/models.py
from django.db import models

# Create your models here.


class Record(models.Model):
    datetime = models.CharField(max_length=50, blank=True, null=True)
    num = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'record'

home/views.py
from django.shortcuts import render, HttpResponse
import time
from login_signup.models import Users
from .models import Record
# Create your views here.


def index(request):
    datetime = time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(time.time()))
    if Record.objects.filter(datetime=datetime[:10]):
        res = Record.objects.get(datetime=datetime[:10])
        res.num += 1
        res.save()
    else:
        Record.objects.create(datetime=datetime[:10], num=1)
    if request.session.get('phone_number'):
        phone_number = request.session.get('phone_number')
        user_info = Users.objects.get(phone_number=phone_number)
    else:
        user_info = 0
    return render(request, "home.html", {'userinfo': user_info})
    # request.session.flush()
    # return HttpResponse(1)


def logout(request):
    request.session.flush()
    return HttpResponse(1)

home/templates/home.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>原古石村，许你千年</title>
  <link rel="stylesheet" href="{% static 'css/font.css' %}">
  <!-- <link rel="stylesheet" href="./css/sideNav.css"> -->
  <link rel="stylesheet" href="{% static 'Public_Assets/css/sideNav.css' %}">
  <link rel="stylesheet" href="{% static 'css/home.css' %}">
</head>
<script src="{% static 'js/init.js' %}"></script>
<body>
  <header>
    <a href="#"><img src="{% static 'Public_Assets/img/logo.png' %}" style="position: absolute; left: 47px; top: -10px; transform: scale(0.63,0.63)" alt="logo"></a>
  </header>
  <article class="stone-article">
    <a href="{% url 'others:media' %}">
      <img src="{% static 'img/article.png' %}" alt="许家山石头村" style="transform: scale(0.75,0.75) translate(-120px,160px)">
    </a>
  </article>
  <button id="menu">MENU</button>
  <aside style="transform: translateX( 208px )" class="stone-side right">
    <button class="btn-side fewer ">
      <span class="hamb-top"></span>
      <span class="hamb-middle"></span>
      <span class="hamb-bottom"></span>
    </button>
    <nav class="stone-nav">
      <ul class="stone-nav-list">
        <li><a id="home" href="#">许家山石村</a></li>
        {% if not userinfo == 0 %}
          <li><a id="user" href="{% url 'others:user2' %}"> 欢迎您 {{ userinfo.nickname }}</a></li>
          {% else %}
          <li><a id="user" href="{% url 'login_signup:login_page' %}">登录/注册</a></li>
          {% endif %}
{#          <li><a id="user" href="http://www.baidu.com">登陆</a></li>#}
        <li><a id="main" href="{% url 'others:about' %}">石村简介</a></li>
        <li><a id="stone" href="{% url 'others:shimo' %}">石模展示</a></li>
        <li><a id="main_part" href="{% url 'others:newmain' %}">石村风情</a></li>
        <li><a id="forum" href="{% url 'posts:list' 1 %}">石村社区</a></li>
        <li><a id="build" href="{% url 'mystone:indexmystone' %}">我的石村</a></li>
        <li><a id="help" href="{% url 'others:complain' %}">反馈与建议</a></li>
      </ul>
    </nav>
  </aside>
  {% if userinfo == 0 %}
  <iframe id="entry" style="position: fixed;width: 100vw;height: 100vh;top: 0;left: 0;visibility: hidden" src="{% url 'login_signup:login_page' %}" frameborder="0"></iframe>
{% endif %}
</body>
{#{% if user_info %}#}
{#<script>#}
{#    window.client = "/login_signup/login_page"#}
{##}
{#</script>#}
{#{% endif %}#}
<script src="{% static 'Public_Assets/js/home.js' %}"></script>
</html>