home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout")
]

login_signup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('send_code/', views.send_code),
    path('login/', views.login, name="login"),
    path('register_page/', views.register_page, name='register_page'),
    path('register/', views.register, name="register"),
    path('login_page/', views.login_page, name="login_page")
]

others/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name="about"),
    path('complain/', views.write_advice, name='complain'),
    path('media/', views.media, name='media'),
    path('newmain/', views.newmain, name='newmain'),
    path('user/', views.user1, name='user1'),
    path('user2/', views.user2, name='user2'),
    path('stone/', views.stone, name='shimo'),
    path('main_part/', views.main_part, name='main_part')
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:page>', views.list_page, name='list'),
    path('content/<int:post_id>', views.content_page, name='content'),
    path('release/', views.release, name='release'),
    path('search/', views.search, name='search'),
    path('comment/<int:post_id>', views.follow, name='follow')

]

stone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_signup/', include(('login_signup.urls', 'login_signup'), namespace='login_signup')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('others/', include(('others.urls', 'others'), namespace='others')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('manage/', include(('backmanage.urls', 'backmanage'), namespace='backmanage')),
    path('mystone/', include(('mystone.urls', 'mystone'), namespace='mystone')),
    path('fullview/', include(('fullview.urls', 'fullview'), namespace='fullview'))
]

posts/models.py
from django.db import models

# Create your models here.


class Posts(models.Model):
    title = models.CharField(max_length=20)
    content = models.TextField(blank=True, null=True)
    keywords = models.CharField(max_length=50)
    comments = models.TextField(blank=True, null=True)
    time = models.CharField(max_length=50, blank=True, null=True)
    author = models.IntegerField(blank=True, null=True)
    thumbs = models.IntegerField(blank=True, null=True)
    volume = models.IntegerField(blank=True, null=True)
    nickname = models.CharField(max_length=300, blank=True, null=True)
    head = models.CharField(max_length=700, blank=True, null=True)
    resolved = models.IntegerField(blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'Posts'

posts/views.py
from django.shortcuts import render, redirect, reverse
from django.http import HttpResponse
from .models import Posts
from login_signup.models import Users
import json
import time
# Create your views here.


# 登录检测
def auth(request):
    if not request.session.get('phone_number'):
        return redirect('login_signup:login_page')


# 检测session获取用户数据
def user_seek(request):
    if request.session.get('phone_number'):
        user_info = Users.objects.get(phone_number=request.session.get('phone_number'))
        return user_info
    else:
        return 0


# 获取贡献榜数据
def contribution_seek(request):
    contribution_data = Users.objects.all().order_by('-contribution')
    condata = contribution_data[:5]
    return condata


# 列表显示
def list_page(request, page):
    res = Posts.objects.all().order_by("-id")
    user_info = user_seek(request)
    contribution_data = contribution_seek(request)
    for question in res:
        question.keywords = json.loads(question.keywords)
        question.comments = json.loads(question.comments)
        question.comment_len = len(question.comments)
    allpage = len(res) // 4 + 1
    if page == allpage:
        ress = res[4*(page-1):]
    else:
        ress = res[4*(page-1):4*page]
    # pagelen = range(7)
    pagelen = []
    for i in range(allpage):
        pagelen.append(i+1)
    lenth = len(pagelen)
    return render(request, 'list_page.html', {'lists': ress, 'user_info': user_info,
                                              'contribution': contribution_data,
                                              'page': page, 'pagelen': pagelen,
                                              'lowpage': page-1, 'hignpage': page+1,
                                              'lenth': lenth})


# 帖子显示
def content_page(request, post_id):
    post_res = Posts.objects.get(pk=post_id)
    post_res.comments = json.loads(post_res.comments)
    post_res.comment_len = int(len(post_res.comments))
    post_res.keywords = json.loads(post_res.keywords)
    new_volume = post_res.volume + 1
    revise = Posts.objects.get(pk=post_id)
    revise.volume = new_volume
    revise.save()
    user_info = user_seek(request)
    con = contribution_seek(request)
    return render(request, 'content_page.html', {'post': post_res, 'user_info': user_info,
                                                 'contribution': con})


# 发布帖子
def release(request):
    auth(request)
    phone_number = request.session.get('phone_number')
    user_info = user_seek(request)
    title = request.POST.get('title')
    content = request.POST.get('content')
    keywords = request.POST.get('keywords')
    time_obj = time.localtime(time.time())
    datetime = time.strftime("%Y/%m/%d %H:%M:%S", time_obj)
    keywords.replace(' ', '')
    new_keywords = keywords.split('#')
    new_keywords = new_keywords[1:]
    str_keywords = json.dumps(new_keywords, ensure_ascii=False)
    res = Posts.objects.create(title=title, content=content, time=datetime, author=user_info.id, thumbs=0,
                               comments='[]', keywords=str_keywords, volume=0, nickname=user_info.nickname,
                               head=user_info.head, resolved=0)
    revise = Users.objects.get(phone_number=phone_number)
    revise.posts = json.loads(revise.posts)
    revise.posts.append(int(res.id))
    revise.posts = json.dumps(revise.posts, ensure_ascii=False)
    revise.contribution += 123
    revise.save()
    return redirect(reverse('posts:list', kwargs={'page': 1}))


# 多字段模糊查询搜索
def search(request):
    user_info = user_seek(request)
    keywords = str(request.GET.get('keywords'))
    keys = keywords.split()
    res = []
    for key in keys:
        res1 = Posts.objects.filter(title__icontains=key)
        res2 = Posts.objects.filter(nickname__icontains=key)
        res3 = Posts.objects.filter(content__icontains=key)
        res4 = Posts.objects.filter(comments__icontains=key)
        res5 = Posts.objects.filter(keywords__icontains=key)
        all_res = list(res1) + list(res2) + list(res3) + list(res4) + list(res5)
        res += all_res
    res = list(set(res))
    for ind in res:
        ind.comments = json.loads(ind.comments)
        ind.keywords = json.loads(ind.keywords)
    # res = sorted(res, key=lambda x: x["volume"])
    # for individual in res:
    #     individual.keywords = json.loads(individual.keywords)
    #     individual.comments = json.loads(individual.comments)
    con = contribution_seek(request)
    return render(request, 'search_page.html', {'search_list': res, 'user_info': user_info,
                                                'keywords': keywords, 'contribution': con})


# 评论
def follow(request, post_id):
    auth(request)
    user_info = user_seek(request)
    content = request.POST.get('content')
    post_info = Posts.objects.get(id=post_id)
    post_info.comments = json.loads(post_info.comments)
    time_obj = time.localtime(time.time())
    datetime = time.strftime("%Y/%m/%d %H:%M:%S", time_obj)
    lenth = len(post_info.comments)
    post_info.comments.append({"id": lenth, "time": datetime, "uid": user_info.id, "nickname": user_info.nickname,
                               "head": user_info.head, "content": content})
    post_info.comments = json.dumps(post_info.comments, ensure_ascii=False)
    post_info.save()
    new_post = Posts.objects.get(id=post_id)
    new_post.comments = json.loads(new_post.comments)
    new_post.keywords = json.loads(new_post.keywords)
    new_user = Users.objects.get(id=user_info.id)
    new_user.joinposts = json.loads(new_user.joinposts)
    if post_id not in new_user.joinposts:
        new_user.joinposts.append(post_id)
    new_user.joinposts = json.dumps(new_user.joinposts, ensure_ascii=False)
    new_user.contribution += 74
    new_user.save()
    return redirect(reverse('posts:content', kwargs={"post_id": post_id}))

posts/templates/content_page.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>{{ post.title }}</title>
  <link rel="stylesheet" href="{% static 'src/css/forum-pro.css' %}">
  <link rel="stylesheet" href="{% static 'src/css/commit.css' %}">
</head>
<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>

<body>
  <header class="forum-head">
    <div class="container">
      <span class="forum-logo">
        <a href="#"><img src="{% static 'src/img/logo.png' %}" alt="logo"></a>
      </span>
      <div class="forum-bar">
        <a href="{% url 'posts:list' 1 %}"><h2>石村社区</h2></a>
        <ul>
          <li><a href="{% url 'posts:list' 1 %}">首页</a></li>
          <li><a href="#">标签</a></li>
          <li><a href="#">留言板</a></li>
          <li><a href="#" id="ask-question" class="ask-question">发&nbsp;&nbsp;&nbsp;&nbsp;帖</a></li>
        </ul>
      </div>
      <div class="search">
        <form action="{% url 'posts:search' %}" method="GET">
          <input type="text" name="keywords" placeholder="搜索">
          <button type="submit"><i class="btn-icon seek"></i></button>
        </form>
      </div>
      <div class="register">
        <ul>
          {% if user_info == 0 %}
          <li><a href="{% url 'login_signup:login' %}" class="btn">登&nbsp;&nbsp;录</a></li>
          <li><a href="{% url 'login_signup:register' %}" class="btn">注&nbsp;&nbsp;册</a></li>
            {% else %}
          <li><a href="" class="portrait"><img src="{{ request.session.head }}" alt="portrait">&nbsp;{{ request.session.username }}</a></li>
            {% endif %}
        </ul>
      </div>
    </div>
  </header>

  <section class="forum-sec">
    <div class="container">
      <ul class="ul-inline">
        <li><a href="#">最&nbsp;新</a></li>

        <li><a href="#">最热</a></li>

      </ul>
    </div>
    <span id="forum-sec-vernier" class="vernier"></span>
  </section>

  <main class="forum-page">
    <div class="col-8">

      <div class="user-poster">
        <div class="question">
          <span class="portrait">
            <img src="{{ post.head }}" alt="user">
          </span>
          <h3>{{ post.title }}</h3>
          <p class="time">{{ post.time }}</p>
          <p class="quest-feat">
            <span>{{ post.thumbs }}</span>
            <span>{{ post.volume }}</span>
          </p>
          <ul class="quest-tags ul-inline">
            {% for key in post.keywords %}
            <li>{{ key }}</li>
              {% endfor %}
          </ul>
          <br>
          <br>
          <br>
          <article class="zhuanyi">
            {{ post.content }}
          </article>
          <br>
          <div class="user-commit">
            <h3>评论</h3>
            <br>
            <br>
            <ul class="question">
                {% for comment in post.comments %}
              <li>
                <span class="portrait">
                  <img src="{{ comment.head }}" alt="user">
                </span>
                <h3>{{ comment.nickname }}</h3>
                <p class="time">{{ comment.time }}</p>
                <br>
                <article class="zhuanyi">
{{ comment.content }}
                </article>
              </li>
              {% endfor %}
            </ul>
          </div>
        </div>
        <div class="commit-post">

          <div id="qq">
            <p>有什么新鲜想法告诉大家?</p>
            <div class="message" contentEditable='true'></div>
              <form id="aform"  style="visibility: hidden" action="{% url 'posts:follow' post.id %}" method="post">

                  <input type="text" name="content">
              </form>
            <div class="But">
              <img src="{% static 'src/img/face/bba_thumb.gif' %}" class='bq' />
              <span class='submit'>发表</span>
              <!--face begin-->
              <div class="face">
                <ul>
                  <li><img src="{% static 'src/img/face/smilea_thumb.gif' %}" title="呵呵]"></li>
                  <li><img src="{% static 'src/img/face/tootha_thumb.gif' %}" title="嘻嘻]"></li>
                  <li><img src="{% static 'src/img/face/laugh.gif' %}" title="[哈哈]"></li>
                  <li><img src="{% static 'src/img/face/tza_thumb.gif' %}" title="[可爱]"></li>
                  <li><img src="{% static 'src/img/face/kl_thumb.gif' %}" title="[可怜]"></li>
                  <li><img src="{% static 'src/img/face/kbsa_thumb.gif' %}" title="[挖鼻屎]"></li>
                  <li><img src="{% static 'src/img/face/cj_thumb.gif' %}" title="[吃惊]"></li>
                  <li><img src="{% static 'src/img/face/shamea_thumb.gif' %}" title="[害羞]"></li>
                  <li><img src="{% static 'src/img/face/zy_thumb.gif' %}" title="[挤眼]"></li>
                  <li><img src="{% static 'src/img/face/bz_thumb.gif' %}" title="[闭嘴]"></li>
                  <li><img src="{% static 'src/img/face/bs2_thumb.gif' %}" title="[鄙视]"></li>
                  <li><img src="{% static 'src/img/face/lovea_thumb.gif' %}" title="[爱你]"></li>
                  <li><img src="{% static 'src/img/face/sada_thumb.gif' %}" title="[泪]"></li>
                  <li><img src="{% static 'src/img/face/heia_thumb.gif' %}" title="[偷笑]"></li>
                  <li><img src="{% static 'src/img/face/qq_thumb.gif' %}" title="[亲亲]"></li>
                  <li><img src="{% static 'src/img/face/sb_thumb.gif' %}" title="[生病]"></li>
                  <li><img src="{% static 'src/img/face/mb_thumb.gif' %}" title="[太开心]"></li>
                  <li><img src="{% static 'src/img/face/ldln_thumb.gif' %}" title="[懒得理你]"></li>
                  <li><img src="{% static 'src/img/face/yhh_thumb.gif' %}" title="[右哼哼]"></li>
                  <li><img src="{% static 'src/img/face/zhh_thumb.gif' %}" title="[左哼哼]"></li>
                  <li><img src="{% static 'src/img/face/x_thumb.gif' %}" title="[嘘]"></li>
                  <li><img src="{% static 'src/img/face/cry.gif' %}" title="[衰]"></li>
                  <li><img src="{% static 'src/img/face/wq_thumb.gif' %}" title="[委屈]"></li>
                  <li><img src="{% static 'src/img/face/t_thumb.gif' %}" title="[吐]"></li>
                  <li><img src="{% static 'src/img/face/k_thumb.gif' %}" title="[打哈气]"></li>
                  <li><img src="{% static 'src/img/face/bba_thumb.gif' %}" title="[抱抱]"></li>
                  <li><img src="{% static 'src/img/face/angrya_thumb.gif' %}" title="[怒]"></li>
                  <li><img src="{% static 'src/img/face/yw_thumb.gif' %}" title="[疑问]"></li>
                  <li><img src="{% static 'src/img/face/cza_thumb.gif' %}" title="[馋嘴]"></li>
                  <li><img src="{% static 'src/img/face/88_thumb.gif' %}" title="[拜拜]"></li>
                  <li><img src="{% static 'src/img/face/sk_thumb.gif' %}" title="[思考]"></li>
                  <li><img src="{% static 'src/img/face/sweata_thumb.gif' %}" title="[汗]"></li>
                  <li><img src="{% static 'src/img/face/sleepya_thumb.gif' %}" title="[困]"></li>
                  <li><img src="{% static 'src/img/face/sleepa_thumb.gif' %}" title="[睡觉]"></li>
                  <li><img src="{% static 'src/img/face/money_thumb.gif' %}" title="[钱]"></li>
                  <li><img src="{% static 'src/img/face/sw_thumb.gif' %}" title="[失望]"></li>
                  <li><img src="{% static 'src/img/face/cool_thumb.gif' %}" title="[酷]"></li>
                  <li><img src="{% static 'src/img/face/hsa_thumb.gif' %}" title="[花心]"></li>
                  <li><img src="{% static 'src/img/face/hatea_thumb.gif' %}" title="[哼]"></li>
                  <li><img src="{% static 'src/img/face/gza_thumb.gif' %}" title="[鼓掌]"></li>
                  <li><img src="{% static 'src/img/face/dizzya_thumb.gif' %}" title="[晕]"></li>
                  <li><img src="{% static 'src/img/face/bs_thumb.gif' %}" title="[悲伤]"></li>


                </ul>
              </div>
              <!--face end-->
            </div>
          </div>

        </div>
      </div>

    </div>
    <div class="col-4">

      <div class="widget-feat">
        <ul class="ul-inline">
          <li><img src="{% static 'src/img/icon/applaud.png' %}" alt=""><br>{{ post.thumbs }}</li>
          <li><img src="{% static 'src/img/icon/comment.png' %}" alt=""><br>{{ post.comment_len }}</li>
          <li><img src="{% static 'src/img/icon/view.png' %}" alt=""><br>{{ post.volume }}</li>
          <li><img src="{% static 'src/img/icon/share.png' %}" alt=""><br>分享</li>
        </ul>
      </div>

      <div class="forum-widget-users">
        <h2> 石村社区贡献榜 </h2>
        <ul>
            {% for con in contribution %}
          <a href="">
            <li class="widget-user">
              <img src="{{ con.head }}" alt="user">
              <div class="user-infor">
                <h3>{{ con.nickname }}</h3>
                <h3 style="font-size: 8px">{{ con.personality }}</h3>
              </div>
              <span class="widget">{{ con.contribution }}</span>
            </li>
          </a>
            {% endfor %}



        </ul>
      </div>
    </div>
  </main>
  <br><br><br>
  <footer>
    <ul class="ul-inline">
      <li><a href="#" title="">帮助</a></li>
      <li><a href="#" title="">隐私策略</a></li>
      <li><a href="#" title="">社区原则</a></li>
      <li><a href="#" title="">划水政策</a></li>
      <li><a href="#" title="">我们</a></li>
      <li><a href="#" title="">论坛</a></li>
      <li><a href="#" title="">语言</a></li>
      <li><a href="#" title="">版权相关</a></li>
    </ul>
    <p><img src="{% static 'src/img/icon/copyright.png' %}" alt="">&nbsp;版权 2019</p>
    <img src="{% static 'src/img/logo.png' %}" alt="logo">&nbsp;石村论坛
  </footer>

  <div id="question-box" class="question-box" style="display: none;">
    <div class="overview-edit">
      <h3>发表帖子</h3>
      <form action="{% url 'posts:release' %}" method="POST">
        <input type="text" name="title" required placeholder="标题" autocomplete="off">
        <input type="text" name="keywords" placeholder="标签：#路线 #旅志" autocomplete="off">
        <textarea placeholder="描述..." name="content"></textarea>
        <button type="submit" id="save">提 交</button>
        <button type="submit" id="cancel">取 消</button>
      </form>
      <a href="#" title="关闭" id="close-box" class="close-box"><i class="la la-close"></i></a>
    </div>
  </div>
</body>
<script>
  $(document).ready(function () {

    //评论初始化
    commitInit();

    // 二级导航栏初始化
    $(".forum-sec .container ul li")[0].click();

    // 发帖相关
    $("#ask-question").click(function () {
      $("#question-box").fadeIn();
    })
    $("#close-box").click(function () {
      $("#question-box").fadeOut("fast");
    })
    $("#cancel").click(function () {
      $("#question-box").fadeOut("fast");
    })

    $(".zhuanyi").each(function(){
        this.innerHTML = this.innerHTML.replace("&lt;","<").replace("&gt;",">").replace("&quot","'").replace("&nbsp;"," ")
    })
  })



  function refreshPages(index) {

  }

  function moveVernier(width, left, name) { //移动二级导航游标

    let vernier = $(`${name?name:"#forum-sec-vernier"}`)

    vernier.width(width)
    vernier.css("left", left)
  }

  $(".forum-sec .container ul li").each(function (index) { //二级导航点击事件绑定

    this.addEventListener("click", function (e) {

      e = $(e.target)

      let width = e.width()
      let left = e.offset().left

      moveVernier(width, left);
      refreshPages(index);
    })
  })
  function commitInit(){
    //点击小图片，显示表情
    $(".bq").click(function (e) {
      $(".face").slideDown(); //慢慢向下展开
      e.stopPropagation(); //阻止冒泡事件
    });

    //在桌面任意地方点击，关闭表情框
    $(document).click(function () {
      $(".face").slideUp(); //慢慢向上收
    });

    //点击小图标时，添加功能
    $(".face ul li").click(function () {
      let simg = $(this).find("img").clone();
      $(".message").append(simg); //将表情添加到输入框
    });

    //点击发表按扭，发表内容
    $("span.submit").click(function () {
      let txt = $(".message").html(); //获取输入框内容
      if (!txt) {
        $('.message').focus(); //自动获取焦点
        return;
      }
      let obj = {
        msg: txt
      }
      $('.message').html('') // 清空输入框
        $("#aform input")[0].value=txt
        $("#aform").submit();
    });

        //删除当前数据
        $("body").on('click', '.del', function () {
      let index = $(this).parent().parent().index();
      msgBoxList.splice(index, 1)
      window.localStorage.setItem('msgBoxList', JSON.stringify(msgBoxList)) //将数据保存到缓存
      $(this).parent().parent().remove()
    })
  }
</script>

</html>

posts/templates/list_page.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>石村社区</title>
  <link rel="stylesheet" href="{% static 'src/css/forum-pro.css' %}">
  <!-- <link rel="stylesheet" href="./src/css/slideBox.css" /> -->
</head>
<script src="{% static 'node_modules/jquery/dist/jquery.min.js' %}"></script>
<!-- <script src="./src/js/jquery.SuperSlide.2.1.3.js"></script> -->

<body>
  <header class="forum-head">
    <div class="container">
      <span class="forum-logo">
        <a href="{% url 'home:index' %}"><img src="{% static 'src/img/logo.png' %}" alt="logo"></a>
      </span>
      <div class="forum-bar">
        <a href="{% url 'posts:list' 1 %}"><h2>石村社区</h2></a>
        <ul>
          <li><a href="{% url 'posts:list' 1 %}">首页</a></li>
          <li><a href="#">标签</a></li>
          <li><a href="#">留言板</a></li>
          <li><a href="#" id="ask-question" class="ask-question">发&nbsp;&nbsp;&nbsp;&nbsp;帖</a></li>
        </ul>
      </div>
      <div class="search">
        <form action="{% url 'posts:search' %}" method="GET">
          <input type="text" name="keywords" placeholder="搜索">
          <button type="submit"><i class="btn-icon seek"></i></button>
        </form>
      </div>
      <div class="register">
        <ul>
            {% if user_info == 0 %}
          <li><a href="{% url 'login_signup:login_page' %}" class="btn">登&nbsp;&nbsp;录</a></li>
          <li><a href="{% url 'login_signup:register_page' %}" class="btn">注&nbsp;&nbsp;册</a></li>
            {% else %}
          <li><a href="{% url 'others:user1' %}" class="portrait"><img src="{{ request.session.head }}" alt="portrait">&nbsp;{{ request.session.username }}</a></li>
            {% endif %}
        </ul>
      </div>
    </div>
  </header>

  <section class="forum-sec">
    <div class="container">
      <ul class="ul-inline">
        <li><a href="#">最&nbsp;新</a></li>

        <li><a href="#">最热</a></li>
      </ul>
    </div>
    <span id="forum-sec-vernier" class="vernier"></span>
  </section>

  <main class="forum-page">
    <div class="col-8">
      <div class="forum-questions">
        <ul>
          {% for question in lists %}
          <li class="forum-user-question">
            <img src="{{ question.head }}" alt="user">
            <div class="container">
              <a href="{% url 'posts:content' question.id %}"><h3 class="question-content">{{ question.title }}</h3></a>
              <ul class="react-links ul-inline">
                <li> <i class="react-icon applaud"></i> &nbsp;赞同&nbsp;{{ question.thumbs }}</li>
                <li> <i class="react-icon comment"></i> &nbsp;评论&nbsp;{{ question.comment_len }}</li>
                <li> <i class="react-icon view"></i> &nbsp;浏览&nbsp;{{ question.volume }}</li>
              </ul>
              <br>
              <ul class="quest-tags ul-inline">
                 {% for keys in question.keywords %}
                <li>{{ keys }}</li>
                 {% endfor %}
              </ul>
              <span class="quest-time">{{ question.time }}</span>
            </div>
          </li>
            {% endfor %}



        </ul>
      </div>
      <nav class="pagination">
        <ul class="page-list ul-inline">
            {% if page == 1 %}
           <a href="#">
            <li> 上一页 </li>
          </a>
        {% else %}
                <a href="{% url 'posts:list' lowpage %}">
            <li> 上一页 </li>
          </a>
        {% endif %}
            {% for i in pagelen %}
          {% if page == i %}
                <a href="#">
            <li class="active"> {{ i}}</li>
          </a>
                {% else %}
              <a href="{% url 'posts:list' i %}"><li>{{ i }}</li></a>
                {% endif %}
          {% endfor %}
            <a href="#"><li>4</li></a>
        <a href="#"><li>5</li></a>
        <a href="#"><li>...</li></a>
        {% if page == lenth %}
          <a href="#">
            <li> 下一页 </li>
          </a>
        {% else %}
            <a href="{% url 'posts:list' hignpage %}">
            <li> 下一页 </li>
          </a>
        {% endif %}
        </ul>
      </nav>
    </div>
    <div class="col-4">
      <div class="forum-widget-users">
        <h2> 石村社区贡献榜 </h2>
        <ul>
            {% for con in contribution %}
          <a href="">
            <li class="widget-user">
              <img src="{{ con.head }}" alt="user">
              <div class="user-infor">
                <h3>{{ con.nickname }}</h3>
                <h3 style="font-size: 8px">{{ con.personality }}</h3>
              </div>
              <span class="widget">{{ con.contribution }}</span>
            </li>
          </a>
            {% endfor %}
            </li>
          </a>
        </ul>
      </div>
    </div>
  </main>

  <footer>
    <ul class="ul-inline">
      <li><a href="#" title="">帮助</a></li>
      <li><a href="#" title="">隐私策略</a></li>
      <li><a href="#" title="">社区原则</a></li>
      <li><a href="#" title="">划水政策</a></li>
      <li><a href="#" title="">我们</a></li>
      <li><a href="#" title="">论坛</a></li>
      <li><a href="#" title="">语言</a></li>
      <li><a href="#" title="">版权相关</a></li>
    </ul>
    <p><img src="{% static 'src/img/icon/copyright.png' %}" alt="">&nbsp;版权 2019</p>
    <img src="{% static 'src/img/logo.png' %}" alt="logo">&nbsp;石村论坛
  </footer>
  
  <div id="question-box" class="question-box" style="display: none;">
    <div class="overview-edit">
      <h3>发表帖子</h3>
      <form action="{% url 'posts:release' %}" method="POST">
        <input type="text" name="title" required placeholder="标题" autocomplete="off">
        <input type="text" name="keywords" placeholder="标签：#路线 #旅志" autocomplete="off">
        <textarea placeholder="描述..." name="content" ></textarea>
        <button type="submit" id="save">提 交</button>
        <button type="submit" id="cancel">取 消</button>
      </form>
      <a href="#" title="关闭" id="close-box" class="close-box"><i class="la la-close"></i></a>
    </div>
  </div>

</body>
<script>
  $(document).ready(function () {

    // 二级导航栏初始化
    $(".forum-sec .container ul li")[0].click(); 

    // 发帖相关
    $("#ask-question").click(function(){
      $("#question-box").fadeIn();
    })
    $("#close-box").click(function(){
      $("#question-box").fadeOut("fast");
    })
    $("#cancel").click(function(){
      $("#question-box").fadeOut("fast");
    })
  })

  function refreshPages(index) {

  }

  function moveVernier(width, left, name) { //移动二级导航游标

    let vernier = $(`${name?name:"#forum-sec-vernier"}`)

    vernier.width(width)
    vernier.css("left", left)
  }

  $(".forum-sec .container ul li").each(function (index) { //二级导航点击事件绑定

    this.addEventListener("click", function (e) {

      e = $(e.target)

      let width = e.width()
      let left = e.offset().left

      moveVernier(width, left);
      refreshPages(index);
    })
  })
</script>

</html>