backmanage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('feedback/', views.feedback, name='feedback'),
    path('forum_task/', views.forum_task, name='forum_task'),
    path('system_state/', views.system_state, name='system_state'),
    path('user_manage/', views.user_manage, name='user_manage'),
    path('set_admin/<int:user_id>', views.set_admin, name='set_admin'),
    path('remove_admin/<int:user_id>', views.remove_admin, name='remove_admin'),
    path('forbid_user/<int:user_id>', views.forbid_user, name='forbid_user'),
    path('reset_password/<int:user_id>', views.reset_password, name='reset_password'),
    path('remove_post/<int:post_id>', views.remove_post, name='remove_post'),
    path('about/', views.about, name='guanyu'),
    path('star/<int:feedback_id>', views.star, name='star'),
    path('pass_post/<int:post_id>', views.pass_post, name='pass_post'),
    path('fail_post/<int:post_id>', views.fail_post, name='fail_post'),
    path('advise/', views.advise, name='advise')

]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout")
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:page>', views.list_page, name='list'),
    path('content/<int:post_id>', views.content_page, name='content'),
    path('release/', views.release, name='release'),
    path('search/', views.search, name='search'),
    path('comment/<int:post_id>', views.follow, name='follow')

]

stone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_signup/', include(('login_signup.urls', 'login_signup'), namespace='login_signup')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('others/', include(('others.urls', 'others'), namespace='others')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('manage/', include(('backmanage.urls', 'backmanage'), namespace='backmanage')),
    path('mystone/', include(('mystone.urls', 'mystone'), namespace='mystone')),
    path('fullview/', include(('fullview.urls', 'fullview'), namespace='fullview'))
]

backmanage/models.py
from django.db import models

# Create your models here.


class Feedback(models.Model):
    content = models.TextField(blank=True, null=True)
    time = models.CharField(max_length=30, blank=True, null=True)
    star = models.IntegerField(blank=True, null=True)
    annex = models.CharField(max_length=1000, blank=True, null=True)

    class Meta:
        managed = True
        db_table = 'feedback'

backmanage/views.py
from django.shortcuts import render, HttpResponse, redirect, reverse
from login_signup.models import Users
from posts.models import Posts
from home.models import Record
from django.http import HttpResponseRedirect
import time
import json
from .models import Feedback
import os
import os
from django import forms
import psutil

# Create your views here.


# 封装md5加密函数
def md5(strr):
    import hashlib
    m = hashlib.md5()
    m.update(strr.encode("utf8"))
    return m.hexdigest()


# 登录检测
def auth(request):
    if not request.session.get('phone_number'):
        return redirect('login_signup:login_page')


def index(request):
    if not request.session.get('phone_number'):
        return redirect('login_signup:login_page')
    admins = Users.objects.filter(auth=1)
    users = Users.objects.filter(auth=0)
    return render(request, 'manage.html', {'users': users, 'admins': admins})


def feedback(request):
    advices = Feedback.objects.all()

    return render(request, 'feedback.html', {'advices': advices})


def forum_task(request):
    res = Posts.objects.all()
    for individual in res:
        individual.keywords = json.loads(individual.keywords)
        individual.comments = json.loads(individual.comments)
    return render(request, 'forum-task.html', {'posts': res})


def system_state(request):
    return render(request, 'system-state.html')


def user_manage(request):
    users = Users.objects.all()
    for user in users:
        user.posts = json.loads(user.posts)
        user.posts_num = len(user.posts)
    users_num = len(users)
    posts_num = len(Posts.objects.all())
    date = time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(time.time()))[:10]
    if Record.objects.filter(datetime=date):
        resu = Record.objects.get(datetime=date)
        res = resu.num
    else:
        Record.objects.create(datetime=date, num=0)
        res = 0
    return render(request, 'user-manage.html', {'users': users, 'users_num': users_num,
                                                'posts_num': posts_num, 'skin': res})


# 获取内存、CPU、网络、硬盘使用状况
# def seek_selfinfo(request):

# 设为管理
def set_admin(request, user_id):
    user_info = Users.objects.get(id=user_id)
    user_info.auth = 1
    user_info.save()
    return redirect('backmanage:user_manage')


# 解除管理
def remove_admin(request, user_id):
    user_info = Users.objects.get(id=user_id)
    user_info.auth = 0
    user_info.save()
    return redirect('backmanage:user_manage')


# 屏蔽用户
def forbid_user(request, user_id):
    user_info = Users.objects.get(id=user_id)
    if user_info.forbid == 1:
        user_info.forbid = 0
    else:
        user_info.forbid = 1
    user_info.save()
    return redirect('backmanage:user_manage')


# 重置密码
def reset_password(request, user_id):
    user_info = Users.objects.get(id=user_id)
    user_info.password = md5('12345')
    user_info.save()
    return redirect('backmanage:user_manage')


# 删除帖子
def remove_post(request, post_id):
    post_info = Posts.objects.get(id=post_id)
    author = post_info.author
    join_data = json.loads(post_info.comments)
    join_users = []
    for join in join_data:
        join_users.append(join['uid'])
    author_info = Users.objects.get(id=author)
    author_info.posts = json.loads(author_info.posts)
    for c in author_info.posts:
        if c == int(post_id):
            author_info.posts.remove(c)
    author_info.posts = json.dumps(author_info.posts, ensure_ascii=False)
    author_info.save()
    for join_user in join_users:
        user_info = Users.objects.get(id=join_user)
        user_info.joinposts = json.loads(user_info.joinposts)
        for a in user_info.joinposts:
            if a == post_id:
                user_info.joinposts.remove(a)
        user_info.joinposts = json.dumps(user_info.joinposts, ensure_ascii=False)
        user_info.save()
    Posts.objects.get(id=post_id).delete()
    return HttpResponseRedirect(reverse('backmanage:forum_task'))


def about(request):
    return render(request, 'about.html')


def star(request, feedback_id):
    feedback_info = Feedback.objects.get(id=feedback_id)
    if feedback_info.star == 0:
        feedback_info.star = 1
    else:
        feedback_info.star = 0
    feedback_info.save()
    return redirect('backmanage:feedback')


# 审核通过
def pass_post(request, post_id):
    post_info = Posts.objects.get(id=post_id)
    post_info.resolved = 1
    post_info.save()
    return redirect('backmanage:forum_task')


# 审核不通过
def fail_post(request, post_id):
    post_info = Posts.objects.get(id=post_id)
    post_info.resolved = -1
    post_info.save()
    return redirect('backmanage:forum_task')


def advise(request):
    content = request.POST.get('content')
    datetime = time.strftime("%Y/%m/%d %H:%M:%S", time.localtime(time.time()))
    if request.FILES.get('annex'):
        annex = request.FILES.get('annex')
        timest = str(time.time())[:-8]
        file_path = 'backmanage/static/upload/' + timest + annex.name
        f = open(file_path, 'wb')
        for chunk in annex.chunks():
            f.write(chunk)
        f.close()
        Feedback.objects.create(content=content, star=0, time=datetime, annex='/static/upload/' + timest + annex.name)
    else:
        Feedback.objects.create(content=content, star=0, time=datetime, annex='')
    return redirect('home:index')

backmanage/templates/about.html
<!DOCTYPE html>
<html lang="cn">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>关于石村</title>
</head>
<body>
    <h1>关于许家山石头村
    </h1>
    <p>许家山石头村位于浙江省宁海县东部，是宁波市内现有建筑规模最大、保存最完整的石屋古村。村落历史可追溯至南宋末年，至今已有近千年历史。村中少有现代化建筑，几乎全部保存石村面貌，随处可见的石屋、石巷、石院、石墙、石板桥、石路、石凳，就像是一个石头的世界，具有极大的建筑特色。同时，石村仍保有着传统的生活方式，村民们淳朴热情，是原始山村生活的真实写照。宁海许家山石头村曾被评为第五批“中国历史文化名村”和首批“中国传统村落”。曾是陈逸飞导演的遗作《理发师》的场景拍摄地，如今当地县政府正编制保护与开发策划，保护古村的石文化以及生活方式的前提下推进旅游开发。</p>
</body>
</html>

backmanage/templates/feedback.html
<!DOCTYPE html>
<html lang="en">
<head>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edmin</title>
    <link rel="stylesheet" type="text/css" href="{% static 'views/bootstrap/css/bootstrap.min.css' %}">
    <link type="text/css" href="{% static 'views/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'views/css/theme.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'views/images/icons/css/font-awesome.css' %}" rel="stylesheet">
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
        rel='stylesheet'>
</head>
<body>
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="content">
                        <div class="module message">
                            <div class="module-head">
                                <h3>
                                    反馈与建议</h3>
                            </div>
                            <div class="module-option clearfix">
                                <div class="pull-left">

                                </div>

                            </div>
                            <div class="module-body table">
                                <table class="table table-message">
                                    <tbody>
                                        <tr class="heading" style="width:100%!important;">
                                            <td class="cell-icon" style="width:40px;">
                                                采纳
                                            </td>
                                            <td class="cell-title">
                                                内容
                                            </td>
                                            <td style="width:30px!important;">附件</td>
                                            <td class="cell-time" style="width:130px!important;">
                                                时间
                                            </td>
                                        </tr>
                                        {% for advice in advices %}
                                        {% if advice.star == 1 %}
                                        <tr class="read starred">
                                            {% else %}
                                            <tr class="read">
                                            {% endif %}

                                            <td class="cell-icon" style="width:40px;">
                                                <a href="{% url 'backmanage:star' advice.id %}"><i class="icon-star"></i></a>
                                            </td>

                                            <td class="cell-title">
                                            {{ advice.content }}
                                            </td>
                                            {% if advice.annex == '' %}
                                        <td></td>
                                            {% else %}
                                                <td class="cell-icon hidden-phone hidden-tablet" style="width:30px!important;">
                                                <a download="附件{{ advice.id }}" href="{{ advice.annex }}" target="_blank"><i class="icon-paper-clip"></i></a>
                                            </td>
                                            {% endif %}
                                            <td class="cell-time" style="width:130px!important;">
                                               {{ advice.time }}
                                            </td>
                                        </tr>
                                            {% endfor %}
                                    </tbody>
                                </table>
                            </div>
                            <div class="module-foot">
                            </div>
                        </div>
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
        </div>
        <!--/.container-->
    </div>
    <div id="question-box" class="question-box" style="display: none;position: absolute;z-index:200;">
    <div class="overview-edit">
      <h3>发表帖子</h3>
      <form action="{% url 'posts:release' %}" method="POST">
        <input type="text" name="title" required placeholder="标题">
        <input type="text" name="keywords" placeholder="标签：#路线 #旅志">
        <textarea placeholder="描述..." name="content" ></textarea>
        <button type="submit" id="save">提 交</button>
        <button type="submit" id="cancel">取 消</button>
      </form>
      <a href="#" title="关闭" id="close-box" class="close-box"><i class="la la-close"></i></a>
    </div>
  </div>
    <!--/.wrapper-->
    <script src="{% static 'views/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script>
       $(document).ready(function () {

    // 发帖相关
    $("#ask-question").click(function(){
      $("#question-box").fadeIn();
    })
    $("#close-box").click(function(){
      $("#question-box").fadeOut("fast");
    })
    $("#cancel").click(function(){
      $("#question-box").fadeOut("fast");
    })
  })

  function refreshPages(index) {

  }




    </script>
</body>

backmanage/templates/forum-task.html
<!DOCTYPE html>
<html lang="cn">

<head>

	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Edmin</title>
		<link rel="stylesheet" type="text/css" href="{% static 'views/bootstrap/css/bootstrap.min.css' %}">
		<link type="text/css" href="{% static 'views/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
		<link type="text/css" href="{% static 'views/css/theme.css' %}" rel="stylesheet">
		<link type="text/css" href="{% static 'views/images/icons/css/font-awesome.css' %}" rel="stylesheet">
		<link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
			rel='stylesheet'>
	</head>

<body>

	<div class="wrapper">
		<div class="container">
			<div class="row">
				<div class="span12">
					<div class="content">

						<div class="module message">
							<div class="module-head">
								<h3>社区管理</h3>
							</div>
							<div class="">
								<div class="pull-left">
{#									筛选 : &nbsp;#}
{#									<div class="btn-group">#}
{#										<button class="btn">所有</button>#}
{#										<button class="btn dropdown-toggle" data-toggle="dropdown">#}
{#											<span class="caret"></span>#}
{#										</button>#}
{#										<ul class="dropdown-menu">#}
{#											<li><a href="#">所有</a></li>#}
{#											<li><a href="#">待审核</a></li>#}
{#											<li><a href="#">审合通过</a></li>#}
{#											<li><a href="#">审核未通过</a></li>#}
{#											<li class="divider"></li>#}
{#											<li><a href="#">清空</a></li>#}
{#										</ul>#}
{#									</div>#}
								</div>
{#								<div class="pull-right">#}
{#									<a href="#" class="btn btn-primary">保存修改</a>#}
{#								</div>#}
							</div>
							<div class="module-body table">

								<table class="table table-message">
									<tbody>
										<tr class="heading">
											<td class="cell-icon"></td>
											<td class="cell-title">内容</td>
                                            <td style="text-align: center;width:200px !important;">操作</td>
											<td class="cell-status hidden-phone hidden-tablet">状态</td>
											<td class="cell-time align-right" style="width: 130px">时间</td>
										</tr>
                                        {% for post in posts %}
										{% if post.resolved == 1 %}
                                            <tr class="task">
                                            {% elif post.resolved == 0 %}
                                                <tr class="task resolved">
                                                {% else %}
                                                    <tr class="task resolved">
                                                    {% endif %}
											<td class="cell-icon"><i class="icon-checker high"></i></td>
											<td class="cell-title">
												<div>{{ post.title }}</div>
											</td>
                                        <td><a href="{% url 'backmanage:remove_post' post.id %}" style="margin-left: 50px!important;">删除</a>
{#                                            {% url 'backmanage:remove_post' post.id %}#}
                                            <a href="{% url 'backmanage:pass_post' post.id %}">通过</a>
                                        <a href="{% url 'backmanage:fail_post' post.id %}">不通过</a></td>

                                        {% if post.resolved == 1 %}

											<td class="cell-status hidden-phone hidden-tablet">

                                                <span class="label label-success">审核通过</span>
                                            {% elif post.resolved == 0 %}

                                            <td class="cell-status hidden-phone hidden-tablet">
                                            <span class="label label-warning">待审核</span>
                                                {% else %}
                                            <td class="cell-status hidden-phone hidden-tablet">
                                            <span class="label label-danger">审核不通过</span>
                                                    {% endif %}
                                            </td>
											<td class="cell-time align-right" style="width: 130px">{{ post.time }}</td>
										</tr>
										{% endfor %}


									</tbody>
								</table>


							</div>
							<div class="module-foot">
							</div>
						</div>

					</div>
					<!--/.content-->
				</div>
			</div>
		</div>
	</div>
	<script src="{% static 'views/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'views/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'views/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'views/scripts/flot/jquery.flot.js' %}" type="text/javascript"></script>
	<script src="{% static 'views/scripts/datatables/jquery.dataTables.js' %}" type="text/javascript"></script>
	<script type="text/javascript">
		{#$(document).ready(function () {#}
		{#	$('.table-message tbody tr').click(#}
		{#		function () {#}
		{#			$(this).toggleClass('resolved');#}
		{#		}#}
		{#	);#}
			$(".hidden-phone.hidden-tablet").each(function () {
				this.classList.remove("hidden-tablet")
			})
		});
	</script>
</body>

backmanage/templates/manage.html
<!doctype html>
<html lang="zh">

<head>
	<meta charset="UTF-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<title>后台管理</title>

	<link rel="stylesheet" href="{% static 'css/reset.css' %}">
	<link rel="stylesheet" href="{% static 'css/style1.css' %}">

</head>

<body>
	<ul class="cd-accordion-menu animated">
		<li>
			<img src="{% static 'img/logo.png' %}" id='alogo' alt="logo">&nbsp;&nbsp;后台管理
		</li>

		<li class="has-children">
			<input type="checkbox" name="group-1" id="group-1" checked>
			<label for="group-1">用户管理</label>

			<ul>
				<li class="has-children">
					<a href="#">管理员</a>


				</li>
				<li >
						<a href="#0">用户</a>
				</li>
			</ul>
		</li>

		<li class="has-children">
			<input type="checkbox" name="group-2" id="group-2">
			<label for="group-2">社区管理</label>

			<ul>
				<li class="has-children">
					<a href="#">帖子</a>


				</li>
				<li class="has-children">

					<a href="#">待审核</a>
				</li>
			</ul>
		</li>

		<li class="has-children">
			<input type="checkbox" name="group-3" id="group-3">
			<label for="group-3">系统管理</label>

			<ul>
				<li class="has-children">
					<input type="checkbox" name="sub-group-5" id="sub-group-5">
					<label for="sub-group-5">服务器状态</label>

					<ul>
						<li><a href="#0">网络状态</a></li>
						<li><a href="#0">内存占用状态</a></li>
						<li><a href="#0">硬盘使用状态</a></li>
						<li><a href="#0">CPU使用情况</a></li>
					</ul>
				</li>
				<li class="has-children">
					<a href="#">服务日志</a>


				</li>
			</ul>
		</li>

		<li class="has-children">
			<input type="checkbox" name="group-4" id="group-4">
			<label for="group-4">反馈与建议</label>

			<ul>
				<li><a href="#0">全部</a></li>
				<li><a href="#0">采纳</a></li>
			</ul>
		</li>
	</ul>
	<iframe id="iframe" src="{% url 'backmanage:user_manage' %}" frameborder="0"></iframe>
	<script src="https://cdn.bootcss.com/jquery/3.4.1/jquery.min.js"></script>
	<script src="{% static 'js/main.js' %}"></script>
    <script>
        $("#alogo").on('click', function(){
            window.location.href = "/"
        })

    </script>
</body>

</html>

backmanage/templates/system-state.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edmin</title>
    <link rel="stylesheet" type="text/css" href="{% static 'views/bootstrap/css/bootstrap.min.css' %}">
    <link type="text/css" href="{% static 'views/bootstrap/css/bootstrap-responsive.min.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'views/css/theme.css' %}" rel="stylesheet">
    <link type="text/css" href="{% static 'views/images/icons/css/font-awesome.css' %}" rel="stylesheet">
    <link type="text/css" href='http://fonts.googleapis.com/css?family=Open+Sans:400italic,600italic,400,600'
        rel='stylesheet'>
</head>
<style>
    .logs {
        background-color: white;
        border-radius: 5px;
        box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
    }

    .logs ul {
        list-style: none;
        width: 100%
    }

    .logs ul li {
        width: 24%;
        text-align: center;
        display: inline-block;
        margin: 25px 0;
    }
</style>

<body>
    <div class="wrapper">
        <div class="container">
            <div class="row">
                <div class="span12">
                    <div class="content">

                        <div class="module">
                            <div class="module-head">
                                <h3>
                                    网络状态 </h3>
                            </div>
                            <div class="module-body">
                                <div class="chart inline-legend grid">
                                    <div id="placeholder2" class="graph">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <br />
                        <!--/.module-->
                        <div class="module">
                            <div class="module-head">
                                <h3>
                                    实时CPU数据 </h3>
                            </div>
                            <div class="module-body">
                                <div class="chart">
                                    <div id="placeholder" class="graph">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/.module-->
                        <br />
                        <div class="module">
                            <div class="module-head">
                                <h3>
                                    CPU平均使用情况</h3>
                            </div>
                            <div class="module-body">
                                <div class="chart pie donut">
                                    <div id="pie-default" class="graph">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/.module-->
                        <br />
                        <div class="module">
                            <div class="module-head">
                                <h3>
                                    当前内存占用</h3>
                            </div>
                            <div class="module-body">
                                <div class="chart pie donut">
                                    <div id="pie-donut" class="graph">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/.module-->
                        <br />
                        <div class="module">
                            <div class="module-head">
                                <h3>
                                    外存占用</h3>
                            </div>
                            <div class="module-body">
                                <div class="chart pie donut interactive">
                                    <div id="pie-interactive" class="graph">
                                    </div>
                                    <div id="hover">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--/.module-->
                    </div>
                    <!--/.content-->
                </div>
                <!--/.span9-->
            </div>
            <section class="logs">
                <div class="module-head">
                    <h3>
                        日志</h3>
                </div>
                <ul>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                    <li><img src="{% static 'img/file.png' %}" alt="file"><br>2019-9-18</li>
                </ul>
            </section>
        </div>
        <!--/.container-->
    </div>
    <!--/.wrapper-->

    <script src="{% static 'views/scripts/jquery-1.9.1.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/scripts/jquery-ui-1.10.1.custom.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/bootstrap/js/bootstrap.min.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/scripts/flot/jquery.flot.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/scripts/flot/jquery.flot.pie.js' %}" type="text/javascript"></script>
    <script src="{% static 'views/scripts/common.js' %}" type="text/javascript"></script>

</body>