backmanage/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('feedback/', views.feedback, name='feedback'),
    path('forum_task/', views.forum_task, name='forum_task'),
    path('system_state/', views.system_state, name='system_state'),
    path('user_manage/', views.user_manage, name='user_manage'),
    path('set_admin/<int:user_id>', views.set_admin, name='set_admin'),
    path('remove_admin/<int:user_id>', views.remove_admin, name='remove_admin'),
    path('forbid_user/<int:user_id>', views.forbid_user, name='forbid_user'),
    path('reset_password/<int:user_id>', views.reset_password, name='reset_password'),
    path('remove_post/<int:post_id>', views.remove_post, name='remove_post'),
    path('about/', views.about, name='guanyu'),
    path('star/<int:feedback_id>', views.star, name='star'),
    path('pass_post/<int:post_id>', views.pass_post, name='pass_post'),
    path('fail_post/<int:post_id>', views.fail_post, name='fail_post'),
    path('advise/', views.advise, name='advise')

]

home/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('logout/', views.logout, name="logout")
]

login_signup/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('send_code/', views.send_code),
    path('login/', views.login, name="login"),
    path('register_page/', views.register_page, name='register_page'),
    path('register/', views.register, name="register"),
    path('login_page/', views.login_page, name="login_page")
]

mystone/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.indexmystone, name="indexmystone"),
    path('new/', views.newindex, name='newindex'),
    path('savegame/', views.savegame, name='savegame'),
    path('savedata/', views.savedata, name='savedata')
]

others/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('about/', views.about, name="about"),
    path('complain/', views.write_advice, name='complain'),
    path('media/', views.media, name='media'),
    path('newmain/', views.newmain, name='newmain'),
    path('user/', views.user1, name='user1'),
    path('user2/', views.user2, name='user2'),
    path('stone/', views.stone, name='shimo'),
    path('main_part/', views.main_part, name='main_part')
]

posts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('<int:page>', views.list_page, name='list'),
    path('content/<int:post_id>', views.content_page, name='content'),
    path('release/', views.release, name='release'),
    path('search/', views.search, name='search'),
    path('comment/<int:post_id>', views.follow, name='follow')

]

stone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login_signup/', include(('login_signup.urls', 'login_signup'), namespace='login_signup')),
    path('', include(('home.urls', 'home'), namespace='home')),
    path('others/', include(('others.urls', 'others'), namespace='others')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('manage/', include(('backmanage.urls', 'backmanage'), namespace='backmanage')),
    path('mystone/', include(('mystone.urls', 'mystone'), namespace='mystone')),
    path('fullview/', include(('fullview.urls', 'fullview'), namespace='fullview'))
]

others/models.py
from django.db import models

# Create your models here.

others/views.py
from django.shortcuts import render, HttpResponse
from login_signup.models import Users
from posts.models import Posts
from backmanage.models import Feedback
import json
# Create your views here.


def about(request):
    return render(request, 'about.html')


def write_advice(request):
    return render(request, 'complain.html')


def media(request):
    return render(request, 'media.html')


def newmain(request):
    return render(request, 'newmain.html')


def user1(request):
    phone_number = request.session.get('phone_number')
    user_info = Users.objects.get(phone_number=phone_number)
    user_info.posts = json.loads(user_info.posts)
    user_info.joinposts = json.loads(user_info.joinposts)
    postin = []
    for post in user_info.posts:
        postabc = Posts.objects.get(id=post)
        postin.append(postabc)
    return render(request, 'user.html', {'user_info': user_info, 'post_info': postin})
    # print(postin)
    # return HttpResponse(1)


def user2(request):
    phone_number = request.session.get('phone_number')
    user_info = Users.objects.get(phone_number=phone_number)
    user_info.posts = json.loads(user_info.posts)
    user_info.joinposts = json.loads(user_info.joinposts)
    return render(request, 'user2.html', {'user_info': user_info})


def stone(request):
    return render(request, 'stone.html')


def main_part(request):
    return render(request, 'main_part.html')

others/templates/about.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>石村简介</title>
</head>
{#<script src="../userEntry/js/init.js"></script>#}
<style>
  * {
    margin: 0;
    padding: 0
  }
  body{
    background-color: rgb(36, 36, 36)
  }
  body{
    transition: all 0.5s
  }
  @font-face {
    font-family: 'scfzxfxs';
    src: url("{% static 'font/about.woff' %}");
  }

  .about {
    float: left;
    height: 100vh;
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center center;
  }
  .about.center{
    position: relative;
  }
  .about h1 {
    font-size: 60px;
    font-family: 'scfzxfxs';
    font-weight: 100
  }

  .aboutTitle-left {
    float: right;
    margin: 100px 10px 20px 0;
    color: whitesmoke
  }

  .aboutTitle-right {
    margin: 100px 0 20px 0;
    color: #87816B
  }

  .aboutText {
    transform: translateX(-120px);
    width: 300px;
    letter-spacing: 7px;
    font-size: 17px;
  }
  .aboutText::after{
    content: "";
    position: absolute;
    width: 78px;
    height: 94px;
    left: 78px;
    bottom: -75px;
    background: url("{% static 'img/about1.png' %}") center center no-repeat;
    background-size: 70% 70%;
    transform: rotateZ(-7deg)
  }
  .aboutToMain{
    display: block;
    background: rgba(0, 0, 0, 0.5);
    padding: 10px 20px;
    padding-right: 120px;
    position: absolute;
    border-radius: 5px;
    right: 0;
    transform: translate(200px,-220px)
  }
  .aboutToMain a{
    font-family: 'scfzxfxs';
    font-size: 80px;
    font-weight: 100;
    color: whitesmoke;
    text-decoration: none;
  }
  .aboutToMain a::after{
    content: "";
    display: inline;
    position: absolute;
    background: no-repeat url("{% static 'img/go.png' %}") center center;
    background-size: 80% 70%;
    transform: translateY(-7px);
    width: 100px;
    height: 100px;
  }
  .aboutToMain a:hover{
    opacity: 0.7;
  }
  @media screen and (min-width: 960px) {
    .about.left {
      width: 15%;
      background-color: #87816B
    }

    .about.center {
      width: 55%;
      background-image: url("{% static 'img/about_center.png' %}")
    }

    .about.right {
      width: 30%;
      background-image: url("{% static 'img/about_right.png' %}")
    }
  }
  @media screen and (max-width: 960px) {
    .about.left {
      width: 40%;
      background-color: #87816B
    }

    .about.center {
      width: 60%;
      background-image: url("{% static 'img/about_center.png' %}")
    }

    .about.right {
      width: 0%;
    }
    .aboutTitle-left{
      margin-right: 0
    }
  }
</style>

<body>
  <div class="about left">
    <h1 class="aboutTitle-left">&#30707;村</h1>
  </div>
  <div class="about center">
    <h1 class="aboutTitle-right">简介</h1>
    <p class="aboutText">
      许家山位于山顶，周围都是山地，植被保护得很好，草木茂盛，古枫参天，翠竹亭亭，石景幽幽，炊烟袅袅，环境清静，走进许家山仿佛走进一个世外桃源，许家山最大的特点是原始、荒野之美，房屋很少用钢筋水泥等现代材料。全村绝大部分都是石屋，石屋的墙体材料用黑色玄武岩堆垒而成。许家山是宁波市内现有保存最完整的石屋古村，也是浙东沿海山地石屋建筑群落的典范,堪称石头王国。
    </p>
    <h1 class="aboutToMain"> <a id="go" href="#">石村风情</a> </h1>
  </div>
  <div class="about right">
  </div>
</body>
<script>
  document.getElementById("go").addEventListener("click",function(e){
    document.getElementsByTagName("body")[0].style.transform = "translateX( -100% )"
    setTimeout(() => {
      e.target.href = "{% url 'others:newmain' %}"
      e.target.click();
    }, 500);
  })
</script>

</html>

others/templates/complain.html
<!DOCTYPE html>

<html>

<head>

	<meta charset="utf-8" />

	<title>反馈与建议</title>
	<link rel="stylesheet" href="{% static 'style.css' %}">
	<link rel="stylesheet" href="{% static 'Public_Assets/css/sideNav.css' %}">

	<!--[if IE]><script>

	$(document).ready(function() { 
	$("#form_wrap").addClass('hide');

	})
</script><![endif]-->

</head>

<body style="margin-top: 60px">

	<div id="wrap">

		<h1>投诉与建议</h1>

		<div id='form_wrap'>

			<form action="{% url 'backmanage:advise' %}" method="POST" enctype="multipart/form-data">
                 {% csrf_token %}

				<p>您好,</p>

				<label for="email">您的建议 : </label>

				<textarea  name="content" value="留言内容" id="message" ></textarea>

				<p>附件</p>	

				<label for="name">选取 </label>

				<input type="file" name="annex" value="" id="file_upload" />

        <br>
        <br>
        <br>

				<input type="submit" name ="submit" value="提交" />

			</form>

		</div>

	</div>
	<aside style="transform: translateX( 208px )" class="stone-side right">
    <button class="btn-side fewer ">
      <span class="hamb-top"></span>
      <span class="hamb-middle"></span>
      <span class="hamb-bottom"></span>
    </button>
    <nav class="stone-nav">
      <ul class="stone-nav-list">
        <li><a id="home" href="{% url 'home:index' %}">许家山石村</a></li>
        <li><a id="user" href="{% url 'login_signup:login_page' %}">登录/注册</a></li>
        <li><a id="main" href="{% url 'others:about' %}">石村简介</a></li>
        <li><a id="stone" href="../stone/stone.html">石模展示</a></li>
        <li><a id="main_part" href="{% url 'others:newmain' %}">石村风情</a></li>
        <li><a id="forum" href="{% url 'posts:list' 1 %}">石村社区</a></li>
        <li><a id="build" href="../Minecraft/index.html">我的石村</a></li>
        <li><a id="help" href="#">反馈与建议</a></li>
      </ul>
    </nav>
  </aside>
	<iframe id="entry" style="position: fixed;width: 100vw;height: 100vh;top: 0;left: 0;visibility: hidden" src="{% url 'login_signup:login_page' %}" frameborder="0"></iframe>
<div style="position:fixed;height:90px;width:100%;left:0;bottom:10px"><div class="footer-banner" style="width:728px; margin:0px auto"></div></div>

<!-- <script src="http://www.jq22.com/jquery/1.7.2/jquery.min.js"></script> -->
<script src="{% static 'Public_Assets/js/jquery.min.js' %}"></script>
<script src="{% static 'Public_Assets/js/home.js' %}"></script>
</body>

</html>

others/templates/media.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>medio</title>


  <link rel="stylesheet" href="{% static 'css/media.css' %}">

</head>
<script src="{% static 'init.js' %}"></script>
<style>
  * {
    margin: 0;
    padding: 0;
  }
</style>

<body>

  <!--logo-->
  <div class="big-bg">

    <textarea id="text" class="textarea" cols="30" rows="10">
    </textarea>
<div id="content">


  <div style="width: 100vw;height: 90px;">
    <div class="comments1 show">
      <img src="{% static 'img/user.JPG' %}" width="70" height="70"
        style="border-radius: 80px; bottom:5px;position: absolute;left: 10px;">
      <span class="user-name">
        萝卜鱼
      </span>
      <img class="close" src="{% static 'img/close.png' %}" width="20">
      <span class="text">
        <p>远古石村，许你千年的魅力!</p>
      </span>
    </div>
  </div>


</div>
    <button type="button" class="button">
      <p style="font-size: 16px;color: white;">发送</p>
    </button>



    <div class="logo" style="position: absolute;left: 0;top: 0;">
      <a href="{% url 'home:index' %}"><img src="{% static 'img/logo.png' %}" class="logo-img" style="transform: scale(0.9,0.9) translate(40px,0px)" alt="logo"></a>
      <div>
        <video style=" outline:none;" width=100%; controls src="https://stone-1258976754.cos.ap-shanghai.myqcloud.com/stone_media.mp4"></video>
      </div>
    </div>

  </div>
</body>
<script>
  document.getElementById("text").value = "\n  "
  document.getElementsByClassName("button")[0].addEventListener("click", function () {
    document.getElementById("content").innerHTML = `
      <div style="width: 100vw;height: 90px;">
        <div class="comments1 show">
          <img src="https://stone-1258976754.cos.ap-shanghai.myqcloud.com/zrk.jpg" width="70" height="70"
            style="border-radius: 80px; bottom:5px;position: absolute;left: 10px;">
          <span class="user-name">
            K
          </span>
          <img class="close" src="{% static 'img/close.png' %}" width="20">
          <span class="text">
            <p>${document.getElementById("text").value}</p>
          </span>
        </div>
      </div>
    ` + document.getElementById("content").innerHTML
    document.getElementById("text").value = "\n  "
  })

</script>

</html>

others/templates/newmain.html
<!DOCTYPE html>
<html lang="cn" >

<head>
  <meta charset="UTF-8">
  <title>石村导引</title>
  
  
  
      <link rel="stylesheet" href="{% static 'css/style.css' %}">

  
</head>

<body background="{% static 'img/介绍目录beijing.jpg' %}" >

<div class="title">
  <img src="{% static 'img/jvzi.png' %}" alt="" style="width: 400px; position: absolute;right: 0;top: -5%;">
</div>

<div style="position: absolute;top:0;height: 100vh;">
  <div class="main1" >
    <div class="main2">

    <div class="content" style="position:absolute">
          <div>
                <img src="{% static 'img/目录.png' %}" style="height:700px;" alt="" onclick="window.location.href='{% url 'home:index' %}'">
          </div>
    </div>
  </div>


  <div class="main2">
    <div class="fullview" style="position:absolute" >
        <div> 
            <img src="{% static 'img/全景图.png' %}" style="height:700px;" alt="" onclick="window.location.href='{% url 'fullview:index' %}'">
        </div>
    </div>
  </div>

    

<div  class="main2">
    <div class="stone-model" style="position:absolute" onclick="window.location.href='{% url 'others:shimo' %}'">
        <div>
            <img src="{% static 'img/石物模型.png' %}" style="height:700px;" alt="" >
        </div>
    </div>
</div>

    
<div class="main2">
    <div class="stone-house" style="position:absolute">
        <div>
            <img src="{% static 'img/石屋.png' %}" style="height:700px;" alt="" onclick="window.location.href='/others/main_part/#a2'">
        </div>
    </div>
</div>
    
<div class="main2">
    <div class="corner" style="position:absolute">
        <div>
          <img src="{% static 'img/一隅.png' %}" style="height:700px;" alt="" onclick="window.location.href='/others/main_part/#a1'">
        </div>
    </div>
</div>
    
<div class="main2">
    <div class="museum" style="position:absolute">
        <div>
            <img src="{% static 'img/bowuguan.png' %}" style="height:700px;" alt="" onclick="window.location.href='{% url 'others:main_part' %}'">
        </div>
    </div>
</div>
    

</div>
   
  </div>

      
  



    




  

    <script  src="js/index.js"></script>




</body>

</html>

others/templates/stone.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>石模展示</title>
  <link rel="stylesheet" href="{% static 'css/sideNav.css' %}">
  <link rel="stylesheet" href="{% static 'css/style2.css' %}">
</head>
<script src="{% static 'Public_Assets/js/jquery.min.js' %}"></script>
<script src="{% static 'node_modules/three/build/three.min.js' %}"></script>
<script src="{% static 'node_modules/three/examples/js/controls/OrbitControls.js' %}"></script>
<script src="{% static 'node_modules/three/examples/js/loaders/GLTFLoader.js' %}"></script>
<script src="{% static 'node_modules/three/examples/js/loaders/DRACOLoader.js' %}"></script>
{#<script src="../userEntry/js/init.js"></script>#}

<body>

  <div class="cont s--inactive">
    <!-- cont inner start -->
    <div class="cont__inner">
      <!-- el start -->
      <div class="el">
        <div class="el__overflow">
          <div class="el__inner">
            <div class="el__bg"></div>
            <div class="el__preview-cont">
              <h2 class="el__heading">石&nbsp;&nbsp;碾</h2>
            </div>
            <div class="el__content">
              <div class="el__text">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;石碾，是一种用石头和木材等制作的使谷物破碎或去皮用的工具，也是许家山石村常见的器具。<br>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;偶然傍晚经过人家院落，总能见到，或是老农推着石碾，擦一擦脸上劳动的汗水，看着面前的谷物流露的微笑，或是孩童绕着石碾嬉戏玩耍，欢声笑语不绝耳。石碾用的久了，村里的石匠师傅会重新錾出碾齿，赋予石碾以新的生命活力。
              </div>
              <div class="el__close-btn"></div>
            </div>
          </div>
        </div>
        <div class="el__index">
          <div class="el__index-back">1</div>
          <div class="el__index-front">
            <div class="el__index-overlay" data-index="1">1</div>
          </div>
        </div>
      </div>
      <!-- el end -->
      <!-- el start -->
      <div class="el">
        <div class="el__overflow">
          <div class="el__inner">
            <div class="el__bg"></div>
            <div class="el__preview-cont">
              <h2 class="el__heading">石&nbsp;&nbsp;臼</h2>
            </div>
            <div class="el__content">
              <div class="el__text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;有人说：“石椿乃宅中之钟。”石椿，也叫石臼，是用以砸、捣食材的工具。走进许家山石村每户人家，几乎都可以看到石椿这种器具。在日常生活中，村民们会用石椿捣小数量的食材谷物，使用起来也不会太过费劲。研磨了几十代人生计的石椿，仍安静地躺在许家山石村的宅院中，也活在村民们的心中，没有被遗忘。
              </div>
              <div class="el__close-btn"></div>
            </div>
          </div>
        </div>
        <div class="el__index">
          <div class="el__index-back">2</div>
          <div class="el__index-front">
            <div class="el__index-overlay" data-index="2">2</div>
          </div>
        </div>
      </div>
      <!-- el end -->
      <!-- el start -->
      <div class="el">
        <div class="el__overflow">
          <div class="el__inner">
            <div class="el__bg"></div>
            <div class="el__preview-cont">
              <h2 class="el__heading">石&nbsp;&nbsp;磨</h2>
            </div>
            <div class="el__content">
              <div class="el__text">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;石磨，是用于把米、麦、豆等磨成粉的一种工具，是中国劳动人民的智慧结晶。在许家山石村，几乎家家户户都可以看到石磨的存在，一般直径80cm左右。每到谷物丰收季节，总能听到院中石磨磨谷的声音，伴随着村民们推石磨时淳朴的喊声。石屋旁的石磨，浸润了村民们的汗水，也蕴藏了石村的灵魂。
              </div>
              <div class="el__close-btn"></div>
            </div>
          </div>
        </div>
        <div class="el__index">
          <div class="el__index-back">3</div>
          <div class="el__index-front">
            <div class="el__index-overlay" data-index="3">3</div>
          </div>
        </div>
      </div>
      <!-- el end -->
      <!-- el start -->
      <div class="el">
        <div class="el__overflow">
          <div class="el__inner">
            <div class="el__bg"></div>
            <div class="el__preview-cont">
              <h2 class="el__heading">石&nbsp;&nbsp;井</h2>
            </div>
            <div class="el__content">
              <div class="el__text">
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;石井，是从古至今流传的文化遗产。古人以锄下挖，至有甘泉，即为井，以石围之，即为石井。石井不仅是许家山石村的当地特色，也是村民们的水源来源。石井帮助了村民们的日常生养耕作，也成为石村当地的建筑特色之一，映衬着当地石村的石元素并融为一体，石井也成为了村子中不可或缺的一部分，更加体现宁海许家村的石文化。
              </div>
              <div class="el__close-btn"></div>
            </div>
          </div>
        </div>
        <div class="el__index">
          <div class="el__index-back">4</div>
          <div class="el__index-front">
            <div class="el__index-overlay" data-index="4">4</div>
          </div>
        </div>
      </div>
      <!-- el end -->
      <!-- el start -->
      <div class="el">
        <div class="el__overflow">
          <div class="el__inner">
            <div class="el__bg"></div>
            <div class="el__preview-cont">
              <h2 class="el__heading">&nbsp;&nbsp;&nbsp;&nbsp;更多的模型，欢迎您来贡献</h2>
            </div>
            <div class="el__content">
              <div class="el__text">Whatever</div>
              <div class="el__close-btn"></div>
            </div>
          </div>
        </div>
        <div class="el__index">
          <div class="el__index-back">5</div>
          <div class="el__index-front">
            <div class="el__index-overlay" data-index="5">5</div>
          </div>
        </div>
      </div>
      <!-- el end -->
    </div>
    <!-- cont inner end -->
  </div>

  <!-- 侧边导航栏 -->
  <aside style="transform: translateX( 208px );z-index: 99999;" class="stone-side right">
    <button class="btn-side fewer ">
      <span class="hamb-top"></span>
      <span class="hamb-middle"></span>
      <span class="hamb-bottom"></span>
    </button>
    <nav class="stone-nav">
      <ul class="stone-nav-list">
        <li><a id="home" href="#">许家山石村</a></li>
        {% if not user_info == 0 %}
          <li><a id="user" href="{% url 'others:user2' %}"> 欢迎您，{{ userinfo.nickname }}</a></li>
          {% else %}
          <li><a id="user" href="{% url 'login_signup:login_page' %}">登录/注册</a></li>
          {% endif %}
{#          <li><a id="user" href="http://www.baidu.com">登陆</a></li>#}
        <li><a id="main" href="{% url 'others:about' %}">石村简介</a></li>
        <li><a id="stone" href="{% url 'others:shimo' %}">石模展示</a></li>
        <li><a id="main_part" href="{% url 'others:newmain' %}">石村风情</a></li>
        <li><a id="forum" href="{% url 'posts:list' 1 %}">石村社区</a></li>
        <li><a id="build" href="{% url 'mystone:indexmystone' %}">我的石村</a></li>
        <li><a id="help" href="{% url 'others:complain' %}">反馈与建议</a></li>
      </ul>
    </nav>
  </aside>
  <iframe id="entry" style="position: fixed;width: 100vw;height: 100vh;top: 0;left: 0;visibility: hidden"
    src="{% url 'login_signup:login_page' %}" frameborder="0"></iframe>
</body>
<script src="{% static 'js/home.js' %}"></script>
<script src="{% static 'js/index2.js' %}"></script>
<script src="{% static 'render.js' %}"></script>
<script>
    $(document).ready(function () {

     if(location.href.indexOf("#reloaded")==-1){
        location.href=location.href+"#reloaded";
        location.reload();
    }
 })

</script>
</html>

others/templates/user.html
<!DOCTYPE html>
<html lang="cn">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>个人界面</title>
  <link rel="stylesheet" href="{% static 'css/user.css' %}">
  <script src="http://apps.bdimg.com/libs/jquery/2.1.4/jquery.min.js"></script>
  <link href="{% static 'bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'cropper/cropper.min.css' %}" rel="stylesheet">
  <link href="{% static 'sitelogo/sitelogo.css' %}" rel="stylesheet">
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/templatemo-style.css' %}" rel="stylesheet">
  <script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/vendor/modernizr.min.js' %}"></script>
  <script src="{% static 'cropper/cropper.min.js' %}"></script>
  <script src="{% static 'sitelogo/sitelogo.js' %}"></script>
</head>
{#<script src="../userEntry/js/init.js"></script>#}
<style>
  * {
    margin: 0;
    padding: 0;
  }
</style>

<body>
  <aside class="stone-aside-user">
    <div class="portraitBox">
      <span class="portrait" style="background-image: url('{{ user_info.head }}')"></span>
      <div class="userName">{{ user_info.nickname }}</div>
    </div>
    <ul>
      <a href="{% url 'others:user2' %}">
        <li>详细资料</li>
      </a>
      <a href="{% url 'others:user1' %}">
        <li>论坛消息</li>
      </a>
    </ul>
    <a class="home" href="{% url 'posts:list' 1 %}"><img src="{% static 'img/back.png' %}" alt="返回主页"></a>
  </aside>
  <main>
    <div id="scroll1" style="width: calc( 100vw - 300px ); height:100vh;overflow-y: scroll">
    <div id="first-section1">
      <div class="container" style="width: 100% !important">
        <div class="row">
          <div class="triangle"></div>
        </div>
        <div class="row">
          <div class="col-md-12">
            <section id="cd-timeline" class="cd-container">

                    {% for i in post_info %}
                <div class="cd-timeline-block">
                  <div class="cd-timeline-img cd-location" style="text-align: center;padding: 15px 0px">
                      <span class="times"></span>
                </div>
  
                <div class="cd-timeline-content service-box-content">
                  <h2>{{ i.title }}</h2>
                  <p>{{ i.content }}</p>
                </div>
              </div>
                {% endfor %}


            </section>
          </div>
        </div>
      </div>
    </div>
  </div>
  </main>
  <script type="text/javascript" src="{% static 'js/custom.js' %}"></script>
</body>

</html>